// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_KULdAyCBA2-pf8-eJ6QuiNLH0aU5gw',
    appId: '1:750499397602:web:de574833fc62007f87c3bb',
    messagingSenderId: '750499397602',
    projectId: 'gramdevta-9facd',
    authDomain: 'gramdevta-9facd.firebaseapp.com',
    storageBucket: 'gramdevta-9facd.appspot.com',
    measurementId: 'G-PVBFT6LRHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQ-5FeMPk_CYzpQo0qmzEQouTV1xB00Q',
    appId: '1:750499397602:android:8d50b47e9a04d90b87c3bb',
    messagingSenderId: '750499397602',
    projectId: 'gramdevta-9facd',
    storageBucket: 'gramdevta-9facd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjC4463G9PPXN_1mYP9AZccApmaGvmAG0',
    appId: '1:750499397602:ios:9c410cea22ab0dce87c3bb',
    messagingSenderId: '750499397602',
    projectId: 'gramdevta-9facd',
    storageBucket: 'gramdevta-9facd.appspot.com',
    iosClientId: '750499397602-eonu1827d2drgqc2d0m7v6jgc5boao41.apps.googleusercontent.com',
    iosBundleId: 'com.example.gramdevta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjC4463G9PPXN_1mYP9AZccApmaGvmAG0',
    appId: '1:750499397602:ios:9c410cea22ab0dce87c3bb',
    messagingSenderId: '750499397602',
    projectId: 'gramdevta-9facd',
    storageBucket: 'gramdevta-9facd.appspot.com',
    iosClientId: '750499397602-eonu1827d2drgqc2d0m7v6jgc5boao41.apps.googleusercontent.com',
    iosBundleId: 'com.example.gramdevta',
  );
}
